### PR TITLE
Waits for Load Balancer Deletions via Finalizers

### PR DESCRIPTION
**Pull request by BugRoger**
This commit changes the wait behaviour when deleteing load balancers.
Previously service deleteion didn't use finalizers and no feedback was
given. The service disapeared immediately. The deorbiter used a fixed
timeout of 2min to wait for load balancer cleanup.

Since the loadbalancer driver in CCEE was changed to Octavia, that grace
period is not enough anymore. Deleteion takes longer and in case of 1.16
never completes if the LoadBalancer is not completely provisioned, e.g.
due to quota limitations. Especially a FIP is expected to be attached
and causes the deletion to never complete.

This fix depends on Kubernetes 1.17 to be fully functional. For
Kubernetes < 1.17 the Deorbiter will wait 24h for the service to be
deleted. For 1.16 it is possible to set the `use-octavia` flag as
a workaround.

### CODE REVIEW

**Comment by databus23** [comment]
@BugRoger Whats this this little nugget I found in the PR list? Is it ready to be merged?

**Comment by BugRoger** [comment]
Can go in, I guess.

**Comment by databus23** [comment]
Should we maybe keep the current behaviour for <1.16 clusters (we do set use-octavia) for a while now. I just would like to avoid customer inquiries about the old cluster stuck in terminating.

**Comment by databus23** [comment]
rebased on master

**Review by databus23 — APPROVED** [review]

**Pull request merged**
