### PR TITLE
Update to go-swagger 0.12.0

### PR DESCRIPTION
**Pull request by databus23**
* lock dependencies of generatered code to the go-swagger version
* Unify generated client and server under pkg/api

### CODE REVIEW

**Comment by databus23** [comment]
I releaise this is tough to review. Not really required from my side. I just wanted to track the progress on the update.

**Comment by SchwarzM** [comment]
merging a big part of the code and increase the codebase by 60k lines ?

**Comment by databus23** [comment]
What can I say the increase in code comes from locking the dependencies to the actual versions used by go-swagger. Let me see if maybe there is more vendored then needed.

**Comment by databus23** [comment]
I excluded `golang.org/x/net` `golang.org/x/text` and now we are done do adding 6000 LOC

**Comment by databus23** [comment]
rebased. Pretty sane now, just moving some files around and updating dependencies. @BugRoger please review. I don't want to rebase this again :)

**Pull request merged**
