### PR TITLE
Make torcx support optional

### PR DESCRIPTION
**Pull request by jknipper**
Torcx is going to be removed in future flatcar release, see https://www.flatcar.org/docs/latest/provisioning/sysext/#torcx-deprecation

- [x] Test upgrade by switching a stable vm to alpha channel

### CODE REVIEW

**Comment by Nuckal777** [comment]
Do we need to do something for old nodes upgrading into torcx removal, because they should not get the new script via ignition? 🧐

**Comment by jknipper** [comment]
> Do we need to do something for old nodes upgrading into torcx removal, because they should not get the new script via ignition? 🧐

Good question, I have no idea if existing nodes will be migrated to `systemd-sysext` or not.

**Comment by jknipper** [comment]
fyi @defo89

**Comment by jknipper** [comment]
I tested switching a node to alpha release channel. It's not coming up anymore and is not joining the cluster. This means we need to prepare a fix for existing nodes.

**Comment by defo89** [comment]
Just a thought for the upgrade case - if in both locations the file is not found, should we maybe copy it from same swift location (the region will need to be populated with some env though)?

**Pull request merged**
