### PR TITLE
unify kluster specs

### PR DESCRIPTION
**Pull request by databus23**
This commit unifies the kluster specs used by the apiserver and the CRD.

This change contains some minor breaking api changes:

* `Kluster.Status.Kluster.State` --> `Kluster.Status.Phase`
  * `Ready` state is now `Running` phase
* `Kluster.Status.Kluster.Message` --> `Kluster.Status.Message`
* `Kluster.Spec.Version` --> `Kluster.Status.Version`
*  Removed `Kluster.Spec.Domain`
* `Kluster.Spec.ClusterDNS` --> `Kluster.Spec.DNSAddress`
* `Kluster.Soec.ClusterDNSDomain` --> `Kluster.Spec.DNSDomain`

### CODE REVIEW

**Comment by edda** [comment]
UI is ready to be tested with this change

**Comment by databus23** [comment]
@edda three more changes to the api (See last 3 bullets above). Can you confirm this won't break your stuff? I think you are not using those fields yet.

**Comment by databus23** [comment]
I added some initial tests to the apiserver and made some minor changes to the Spec.
We now run `go test ./...` in the docker build to make sure the build fails when tests fail
@BugRoger @SchwarzM please review

**Comment by databus23** [comment]
By the powers of greyscull I'm merging this PR

**Pull request merged**
