### PR TITLE
Support multiple k8s versions

### PR DESCRIPTION
**Pull request by jknipper**
This PR is about adjusting the kube-master charts to run on all used kubernetes versions.

### CODE REVIEW

**Comment by databus23** [comment]
Tests should clear once we rebase on 
https://github.com/sapcc/kubernikus/pull/396

**Comment by databus23** [comment]
This is ready for review now. @BugRoger @jknipper

**Comment by databus23** [comment]
@BugRoger Are you good with merging this?

**Comment by BugRoger** [comment]
Bring her in!

source

**Comment by databus23** [comment]
Boom!

**Pull request merged**
