### PR TITLE
fix default backend and use it only for 502,503,504

### PR DESCRIPTION
**Pull request by auhlig**
The `out of range error` happend [here](https://github.com/kubernetes/ingress-nginx/blob/master/images/custom-error-pages/main.go#L64). Added a check before.
Also just use the default backend for `502,503,504`.
Issue https://github.com/sapcc/kubernikus/issues/133 /cc @databus23

### CODE REVIEW

**Comment by databus23** [comment]
What do you mean by

> Added a check before.

You linked a kubernetes repo. Did you fork it? Where? Should we maybe file this upstream.

**Comment by auhlig** [comment]
Yep, I forked it. Didn't push it so far. I'll do in a min.

**Comment by databus23** [comment]
@auhlig Would you care to try getting this merged upstream?

**Comment by auhlig** [comment]
will do

**Pull request merged**
