### PR TITLE
Adds Public-Key to GetMetadata Call

### LINKED ISSUE #156: Add Public-Key to GetMetadata API

### PR DESCRIPTION
**Pull request by BugRoger**
This PR adds the public-key to the `getmetadata` call. The intention is to use this as a convenience feature in the UI.

The key will be copied to a free-text field. Alernatively the user will be able to provide a whole different key by herself. 

Fixes #156

### CODE REVIEW

**Comment by BugRoger** [comment]
@edda new json will look like:

```
...,
  "keyPairs": [
    {
      "name": "id_rsa",
      "publicKey": "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvFapuevZeHFpFn438XMjvEQYd0wt7+tzUdAkMiSd007Tx1h79Xm9ZziDDUe4W6meinVOq93MAS/ER27hoVWGo2H/vn/Cz5M8xr2j5rQODnrF3RmfrJTbZAWaDN0JTq2lFjmCHhZJNhr+VQP1uw4z2ofMBP6MLybnLmm9ukzxFYZqCCyfEEUTCMA9SWywtTpGQp8VLM4INCxzBSCuyt3SO6PBvJSo4HoKg/sLvmRwpCVZth48PI0EUbJ72wp88Cw3bv8CLce2TOkLMwkE6NRN55w2aOyqP1G3vixHa6YcVaLlkQhJoJsBwE3rX5603y2KjOhMomqHfXxXn/3GKTWlsQ== michael.j.schmidt@gmail.com"
    }
  ],
...
```

**Comment by databus23** [comment]
Lgtm but I‘n already working on this since before Christmas. I have something similar like this in an umpushed branch. We can use this and I adjust my code but I already assigned all related tickets to me as I already have 90% of th Code done.

**Comment by databus23** [comment]
@edda Please review at merge at you earliest convenience. I will then continue my work on the remaining ssh key stuff based on this PR.

**Comment by BugRoger** [comment]
> @databus23 Lgtm but I‘n already working on this since before Christmas.
Oops, sorry. This PR literally took me 1 minute. I was looking into the API and whether the public-key actually falls out. I don't mind either way.

**Pull request merged**
